[project]
name = "walkie-sdk"
version = "0.1.0"
description = "Python SDK for controlling Walkie robots via WebSocket (ROSBridge) and WebRTC"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "Walkie Team"}
]
keywords = ["robotics", "ros2", "sdk", "rosbridge", "webrtc", "navigation"]
dependencies = [
    "aiohttp>=3.13.2",
    "aiortc>=1.14.0",
    "av>=16.0.1",
    "numpy>=2.0.0", # ปรับลดเพื่อให้เข้ากับโมเดล AI ในอนาคต
    "opencv-python>=4.11.0.86",
    "roslibpy>=2.0.0",
    "pyyaml"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["walkie_sdk"]
